/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cielio.guardanotas.visualizacao;

import br.com.cielio.guardanotas.controle.ControladorNota;
import br.com.cielio.guardanotas.modelo.Nota;
import java.awt.event.MouseListener;
import java.util.Date;
import java.util.Vector;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author kohoutek
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        listarNotas();
        //getItemSelecionado();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPaneJListTitulo = new javax.swing.JScrollPane();
        jListTitulo = new javax.swing.JList();
        jScrollPaneJTextPane = new javax.swing.JScrollPane();
        jTextPaneConteudo = new javax.swing.JTextPane();
        jTextFieldTitulo = new javax.swing.JTextField();
        jButtonAdiciona = new javax.swing.JButton();
        jButtonDeleta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPaneJListTitulo.setMaximumSize(new java.awt.Dimension(500, 600));
        jScrollPaneJListTitulo.setMinimumSize(new java.awt.Dimension(50, 400));
        jScrollPaneJListTitulo.setPreferredSize(new java.awt.Dimension(200, 600));

        jListTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jListTitulo.setAutoscrolls(false);
        jListTitulo.setMaximumSize(new java.awt.Dimension(3000, 30000));
        jListTitulo.setMinimumSize(new java.awt.Dimension(100, 100));
        jListTitulo.setPreferredSize(new java.awt.Dimension(150, 10));
        jListTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListTituloMouseClicked(evt);
            }
        });
        jScrollPaneJListTitulo.setViewportView(jListTitulo);

        jSplitPane1.setLeftComponent(jScrollPaneJListTitulo);

        jTextPaneConteudo.setPreferredSize(new java.awt.Dimension(6, 400));
        jScrollPaneJTextPane.setViewportView(jTextPaneConteudo);

        jSplitPane1.setRightComponent(jScrollPaneJTextPane);

        jButtonAdiciona.setText("Adicionar");
        jButtonAdiciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionaActionPerformed(evt);
            }
        });

        jButtonDeleta.setText("Deletar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAdiciona)
                .addGap(10, 10, 10)
                .addComponent(jButtonDeleta)
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdiciona)
                    .addComponent(jButtonDeleta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionaActionPerformed
        adicionarNota();
    }//GEN-LAST:event_jButtonAdicionaActionPerformed

    private void jListTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListTituloMouseClicked

        if (jListTitulo.getSelectedIndex() > -1) {
            Nota nota;
            
            nota = (Nota) jListTitulo.getSelectedValue();
            jTextPaneConteudo.setText(nota.getConteudo());
        }
    }//GEN-LAST:event_jListTituloMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdiciona;
    private javax.swing.JButton jButtonDeleta;
    private javax.swing.JList jListTitulo;
    private javax.swing.JScrollPane jScrollPaneJListTitulo;
    private javax.swing.JScrollPane jScrollPaneJTextPane;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextPane jTextPaneConteudo;
    // End of variables declaration//GEN-END:variables

    public final void listarNotas() {
        ControladorNota controladorNota = new ControladorNota();

        /*DefaultListModel<Nota> model = new DefaultListModel<>();
        
         for (Nota nota : controladorNota.listar()) {
         model.addElement(nota);
         }*/
        jListTitulo.setListData(new Vector(controladorNota.listar()));

        jListTitulo.setPreferredSize(new java.awt.Dimension(150, (controladorNota.listar().size() * 21)));
    }

    public void adicionarNota() {
        ControladorNota controladorNota = new ControladorNota();

        Nota nota = new Nota();

        Date date = new Date();
        date.getTime();

        nota.setTitulo(jTextFieldTitulo.getText());
        nota.setConteudo(jTextPaneConteudo.getText());
        nota.setData(date);

        controladorNota.adicionar(nota);

        jTextFieldTitulo.setText("");

        listarNotas();
    }

    public final void getItemSelecionado() {
        jListTitulo.addListSelectionListener(new ListSelectionListener() {
            Nota nota = new Nota();

            @Override
            public void valueChanged(ListSelectionEvent arg0) {
                if (!arg0.getValueIsAdjusting()) {
                    nota = (Nota) jListTitulo.getSelectedValue();
                    jTextPaneConteudo.setText(nota.getConteudo());
                }
            }
        });
    }

}
